name: CI

on:
  push:
    branches: [master, staging, trying]
  pull_request:
    branches: [master]
jobs:
  check:
    name: Build Hugo example site and archive output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peaceiris/actions-hugo@v2
      - name: Build Hugo example site
        run: |
          cd exampleSite
          hugo --verbose --baseURL= --themesDir=../../

  ci-success:
    name: CI
    if: ${{ success() }}
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
