name: CI

on:
  push:
    branches: [master, staging, trying]
  pull_request:
    branches: [master]
jobs:
  check:
    name: Build Hugo example site and archive output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peaceiris/actions-hugo@v2
      - name: Build Hugo example site
        run: |
          cd exampleSite
          hugo --verbose --baseURL= --themesDir=../../

  check-flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix --extra-experimental-features "nix-command flakes" flake check

  ci-success:
    name: CI
    if: ${{ success() }}
    needs:
      - check
      - check-flake
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
